name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  ci:
    uses: ucgmsim/meta-ci-action/.github/workflows/ci.yml@v2
    with:
      exclude-init: false
      enable-coverage: true
      cov-package: qcore
      cov-fail-under: 95
